name: Run Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install .[dev]

      # Cache the downloaded model between workflows
    - name: Restore GGUF model cache
      uses: actions/cache@v4
      id: cache-model
      with:
        path: ${{ vars.HF_MODEL_LOCAL_PATH }}
        # Change the HF_GGUF_UPDATE_DATE variable to force update the cache
        key: gguf-${{ vars.HF_MODEL_ID }}-${{ vars.HF_GGUF_FILE }}-${{ vars.HF_GGUF_UPDATE_DATE }}
        restore-keys: |
          gguf-${{ vars.HF_MODEL_ID }}-${{ vars.HF_GGUF_FILE }}-${{ vars.HF_GGUF_UPDATE_DATE }}-

    - name: Download the model
      if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      run: |
        pip install huggingface_hub
        chmod +x ./scripts/get_gguf_model.sh
        ./scripts/get_gguf_model.sh "${{ vars.HF_MODEL_ID }}" "${{ vars.HF_GGUF_FILE }}" "${{ vars.HF_MODEL_LOCAL_PATH }}"

    - name: Test
      # Using default directory for models
      run: |
        pytest --cov --cov-branch --cov-report=xml -v -m "not slow" ./tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  code-style:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run pre-commit to check code style
      run: |
        pip install pre-commit
        pre-commit run --all-files
